[env]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
; board_build.partitions = huge_app.csv

[env:rx]
build_src_filter = +<*> -<tx.cpp>

[env:tx]
build_src_filter = +<*> -<rx.cpp>
