[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

[env:master]
build_src_filter = +<*> -<slave.cpp>

[env:slave]
build_src_filter = +<*> -<master.cpp>
